;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Combat.1",DevComment="")
+GameplayTagList=(Tag="Combat.2",DevComment="")
+GameplayTagList=(Tag="ComboWindow.1",DevComment="")
+GameplayTagList=(Tag="ComboWindow.2",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.Combat.EndBlock",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Equip",DevComment="")
+GameplayTagList=(Tag="Event.Combat.Knockback",DevComment="")
+GameplayTagList=(Tag="Event.Combo.End",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Start",DevComment="")
+GameplayTagList=(Tag="Event.Trace.End",DevComment="")
+GameplayTagList=(Tag="Event.Trace.Start",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attacks.Heavy.1",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attacks.Heavy.2",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attacks.Light.1",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attacks.Light.2",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attacks.Light.3",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Combat.Block",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Combat.IsKnockbacked",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Combat.Lockon",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Lockon",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Cooldown.Lockon",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Cost.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Data.AttackCost",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Data.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Data.DashCooldown",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Data.Heal",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Regen.Stamina",DevComment="")

